### PR TITLE
#156368198: Move staging changes into production for GCP move

### PR DESCRIPTION
**Pull request by VincentHokie**
#### What does this PR do?
It moves changes needed for the production environment from develop into master for the move to Google Cloud

#### Description of Task to be completed?
N/A

#### How should this be manually tested?
N/A

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#156368198](https://www.pivotaltracker.com/story/show/156368198)

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

### CODE REVIEW

**Comment by cjmash** [comment]
LGTM

**Comment by Chidiebube** [comment]
@VincentHokie how will this be tested after merge to master ? cc @cjmash

**Comment by VincentHokie** [comment]
@Chidiebube I will try and deploy my vof master branch on andela-learning with our new master (in deployment scripts) a positive test on that will (should) mean it will work on vof-tracker. cc @cjmash

**Comment by cjmash** [comment]
Yeah we can deploy our fork using this scripts see what happens @Chidiebube

**Pull request merged**
